/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as FleetIndexRouteImport } from './routes/fleet.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as FleetVehicleIdRouteImport } from './routes/fleet.$vehicleId'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as BookVehicleIdRouteImport } from './routes/book.$vehicleId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminFleetIndexRouteImport } from './routes/admin.fleet.index'
import { Route as AdminOrdersRentalsRouteImport } from './routes/admin.orders.rentals'
import { Route as AdminOrdersOnlineRouteImport } from './routes/admin.orders.online'
import { Route as AdminOrdersManualRouteImport } from './routes/admin.orders.manual'
import { Route as AdminOrdersInvoicesRouteImport } from './routes/admin.orders.invoices'
import { Route as AdminHrPayrollRouteImport } from './routes/admin.hr.payroll'
import { Route as AdminHrLoansRouteImport } from './routes/admin.hr.loans'
import { Route as AdminHrLeavesRouteImport } from './routes/admin.hr.leaves'
import { Route as AdminHrEmployeesRouteImport } from './routes/admin.hr.employees'
import { Route as AdminHrDepartmentsRouteImport } from './routes/admin.hr.departments'
import { Route as AdminHrAdvancesRouteImport } from './routes/admin.hr.advances'
import { Route as AdminFleetMaintenanceRouteImport } from './routes/admin.fleet.maintenance'
import { Route as AdminFleetCategoriesRouteImport } from './routes/admin.fleet.categories'
import { Route as AdminDashboardOperationsRouteImport } from './routes/admin.dashboard.operations'
import { Route as AdminDashboardCommercialRouteImport } from './routes/admin.dashboard.commercial'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'
import { Route as AdminCrmLeadsRouteImport } from './routes/admin.crm.leads'
import { Route as AdminCrmCampaignsRouteImport } from './routes/admin.crm.campaigns'
import { Route as AdminCmsHomeRouteImport } from './routes/admin.cms.home'
import { Route as AdminCmsFleetRouteImport } from './routes/admin.cms.fleet'
import { Route as AdminCmsAboutRouteImport } from './routes/admin.cms.about'
import { Route as AdminAccountingReportsRouteImport } from './routes/admin.accounting.reports'
import { Route as AdminAccountingJournalRouteImport } from './routes/admin.accounting.journal'
import { Route as AdminAccountingExpensesRouteImport } from './routes/admin.accounting.expenses'
import { Route as AdminAccountingCoaRouteImport } from './routes/admin.accounting.coa'
import { Route as AdminFleetVehiclesIndexRouteImport } from './routes/admin.fleet.vehicles.index'
import { Route as AdminFleetVehiclesUnitIdRouteImport } from './routes/admin.fleet.vehicles.$unitId'
import { Route as ApiPublicCampaignSlugViewRouteImport } from './routes/api/public/campaign.$slug.view'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetVehicleIdRoute = FleetVehicleIdRouteImport.update({
  id: '/fleet/$vehicleId',
  path: '/fleet/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVehicleIdRoute = BookVehicleIdRouteImport.update({
  id: '/book/$vehicleId',
  path: '/book/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetIndexRoute = AdminFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRentalsRoute = AdminOrdersRentalsRouteImport.update({
  id: '/orders/rentals',
  path: '/orders/rentals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOnlineRoute = AdminOrdersOnlineRouteImport.update({
  id: '/orders/online',
  path: '/orders/online',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersManualRoute = AdminOrdersManualRouteImport.update({
  id: '/orders/manual',
  path: '/orders/manual',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersInvoicesRoute = AdminOrdersInvoicesRouteImport.update({
  id: '/orders/invoices',
  path: '/orders/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrPayrollRoute = AdminHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrLoansRoute = AdminHrLoansRouteImport.update({
  id: '/hr/loans',
  path: '/hr/loans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrLeavesRoute = AdminHrLeavesRouteImport.update({
  id: '/hr/leaves',
  path: '/hr/leaves',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrEmployeesRoute = AdminHrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrDepartmentsRoute = AdminHrDepartmentsRouteImport.update({
  id: '/hr/departments',
  path: '/hr/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrAdvancesRoute = AdminHrAdvancesRouteImport.update({
  id: '/hr/advances',
  path: '/hr/advances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetMaintenanceRoute = AdminFleetMaintenanceRouteImport.update({
  id: '/fleet/maintenance',
  path: '/fleet/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetCategoriesRoute = AdminFleetCategoriesRouteImport.update({
  id: '/fleet/categories',
  path: '/fleet/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardOperationsRoute =
  AdminDashboardOperationsRouteImport.update({
    id: '/dashboard/operations',
    path: '/dashboard/operations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDashboardCommercialRoute =
  AdminDashboardCommercialRouteImport.update({
    id: '/dashboard/commercial',
    path: '/dashboard/commercial',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminCrmLeadsRoute = AdminCrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmCampaignsRoute = AdminCrmCampaignsRouteImport.update({
  id: '/crm/campaigns',
  path: '/crm/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsHomeRoute = AdminCmsHomeRouteImport.update({
  id: '/cms/home',
  path: '/cms/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsFleetRoute = AdminCmsFleetRouteImport.update({
  id: '/cms/fleet',
  path: '/cms/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsAboutRoute = AdminCmsAboutRouteImport.update({
  id: '/cms/about',
  path: '/cms/about',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountingReportsRoute = AdminAccountingReportsRouteImport.update({
  id: '/accounting/reports',
  path: '/accounting/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountingJournalRoute = AdminAccountingJournalRouteImport.update({
  id: '/accounting/journal',
  path: '/accounting/journal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountingExpensesRoute = AdminAccountingExpensesRouteImport.update({
  id: '/accounting/expenses',
  path: '/accounting/expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountingCoaRoute = AdminAccountingCoaRouteImport.update({
  id: '/accounting/coa',
  path: '/accounting/coa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetVehiclesIndexRoute = AdminFleetVehiclesIndexRouteImport.update({
  id: '/fleet/vehicles/',
  path: '/fleet/vehicles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetVehiclesUnitIdRoute =
  AdminFleetVehiclesUnitIdRouteImport.update({
    id: '/fleet/vehicles/$unitId',
    path: '/fleet/vehicles/$unitId',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiPublicCampaignSlugViewRoute =
  ApiPublicCampaignSlugViewRouteImport.update({
    id: '/api/public/campaign/$slug/view',
    path: '/api/public/campaign/$slug/view',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$vehicleId': typeof BookVehicleIdRoute
  '/c/$slug': typeof CSlugRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/fleet/': typeof FleetIndexRoute
  '/news/': typeof NewsIndexRoute
  '/admin/accounting/coa': typeof AdminAccountingCoaRoute
  '/admin/accounting/expenses': typeof AdminAccountingExpensesRoute
  '/admin/accounting/journal': typeof AdminAccountingJournalRoute
  '/admin/accounting/reports': typeof AdminAccountingReportsRoute
  '/admin/cms/about': typeof AdminCmsAboutRoute
  '/admin/cms/fleet': typeof AdminCmsFleetRoute
  '/admin/cms/home': typeof AdminCmsHomeRoute
  '/admin/crm/campaigns': typeof AdminCrmCampaignsRoute
  '/admin/crm/leads': typeof AdminCrmLeadsRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/dashboard/commercial': typeof AdminDashboardCommercialRoute
  '/admin/dashboard/operations': typeof AdminDashboardOperationsRoute
  '/admin/fleet/categories': typeof AdminFleetCategoriesRoute
  '/admin/fleet/maintenance': typeof AdminFleetMaintenanceRoute
  '/admin/hr/advances': typeof AdminHrAdvancesRoute
  '/admin/hr/departments': typeof AdminHrDepartmentsRoute
  '/admin/hr/employees': typeof AdminHrEmployeesRoute
  '/admin/hr/leaves': typeof AdminHrLeavesRoute
  '/admin/hr/loans': typeof AdminHrLoansRoute
  '/admin/hr/payroll': typeof AdminHrPayrollRoute
  '/admin/orders/invoices': typeof AdminOrdersInvoicesRoute
  '/admin/orders/manual': typeof AdminOrdersManualRoute
  '/admin/orders/online': typeof AdminOrdersOnlineRoute
  '/admin/orders/rentals': typeof AdminOrdersRentalsRoute
  '/admin/fleet/': typeof AdminFleetIndexRoute
  '/admin/fleet/vehicles/$unitId': typeof AdminFleetVehiclesUnitIdRoute
  '/admin/fleet/vehicles/': typeof AdminFleetVehiclesIndexRoute
  '/api/public/campaign/$slug/view': typeof ApiPublicCampaignSlugViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$vehicleId': typeof BookVehicleIdRoute
  '/c/$slug': typeof CSlugRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/fleet': typeof FleetIndexRoute
  '/news': typeof NewsIndexRoute
  '/admin/accounting/coa': typeof AdminAccountingCoaRoute
  '/admin/accounting/expenses': typeof AdminAccountingExpensesRoute
  '/admin/accounting/journal': typeof AdminAccountingJournalRoute
  '/admin/accounting/reports': typeof AdminAccountingReportsRoute
  '/admin/cms/about': typeof AdminCmsAboutRoute
  '/admin/cms/fleet': typeof AdminCmsFleetRoute
  '/admin/cms/home': typeof AdminCmsHomeRoute
  '/admin/crm/campaigns': typeof AdminCrmCampaignsRoute
  '/admin/crm/leads': typeof AdminCrmLeadsRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/dashboard/commercial': typeof AdminDashboardCommercialRoute
  '/admin/dashboard/operations': typeof AdminDashboardOperationsRoute
  '/admin/fleet/categories': typeof AdminFleetCategoriesRoute
  '/admin/fleet/maintenance': typeof AdminFleetMaintenanceRoute
  '/admin/hr/advances': typeof AdminHrAdvancesRoute
  '/admin/hr/departments': typeof AdminHrDepartmentsRoute
  '/admin/hr/employees': typeof AdminHrEmployeesRoute
  '/admin/hr/leaves': typeof AdminHrLeavesRoute
  '/admin/hr/loans': typeof AdminHrLoansRoute
  '/admin/hr/payroll': typeof AdminHrPayrollRoute
  '/admin/orders/invoices': typeof AdminOrdersInvoicesRoute
  '/admin/orders/manual': typeof AdminOrdersManualRoute
  '/admin/orders/online': typeof AdminOrdersOnlineRoute
  '/admin/orders/rentals': typeof AdminOrdersRentalsRoute
  '/admin/fleet': typeof AdminFleetIndexRoute
  '/admin/fleet/vehicles/$unitId': typeof AdminFleetVehiclesUnitIdRoute
  '/admin/fleet/vehicles': typeof AdminFleetVehiclesIndexRoute
  '/api/public/campaign/$slug/view': typeof ApiPublicCampaignSlugViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$vehicleId': typeof BookVehicleIdRoute
  '/c/$slug': typeof CSlugRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/fleet/': typeof FleetIndexRoute
  '/news/': typeof NewsIndexRoute
  '/admin/accounting/coa': typeof AdminAccountingCoaRoute
  '/admin/accounting/expenses': typeof AdminAccountingExpensesRoute
  '/admin/accounting/journal': typeof AdminAccountingJournalRoute
  '/admin/accounting/reports': typeof AdminAccountingReportsRoute
  '/admin/cms/about': typeof AdminCmsAboutRoute
  '/admin/cms/fleet': typeof AdminCmsFleetRoute
  '/admin/cms/home': typeof AdminCmsHomeRoute
  '/admin/crm/campaigns': typeof AdminCrmCampaignsRoute
  '/admin/crm/leads': typeof AdminCrmLeadsRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/dashboard/commercial': typeof AdminDashboardCommercialRoute
  '/admin/dashboard/operations': typeof AdminDashboardOperationsRoute
  '/admin/fleet/categories': typeof AdminFleetCategoriesRoute
  '/admin/fleet/maintenance': typeof AdminFleetMaintenanceRoute
  '/admin/hr/advances': typeof AdminHrAdvancesRoute
  '/admin/hr/departments': typeof AdminHrDepartmentsRoute
  '/admin/hr/employees': typeof AdminHrEmployeesRoute
  '/admin/hr/leaves': typeof AdminHrLeavesRoute
  '/admin/hr/loans': typeof AdminHrLoansRoute
  '/admin/hr/payroll': typeof AdminHrPayrollRoute
  '/admin/orders/invoices': typeof AdminOrdersInvoicesRoute
  '/admin/orders/manual': typeof AdminOrdersManualRoute
  '/admin/orders/online': typeof AdminOrdersOnlineRoute
  '/admin/orders/rentals': typeof AdminOrdersRentalsRoute
  '/admin/fleet/': typeof AdminFleetIndexRoute
  '/admin/fleet/vehicles/$unitId': typeof AdminFleetVehiclesUnitIdRoute
  '/admin/fleet/vehicles/': typeof AdminFleetVehiclesIndexRoute
  '/api/public/campaign/$slug/view': typeof ApiPublicCampaignSlugViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/health'
    | '/admin/news'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/book/$vehicleId'
    | '/c/$slug'
    | '/fleet/$vehicleId'
    | '/news/$slug'
    | '/admin/'
    | '/fleet/'
    | '/news/'
    | '/admin/accounting/coa'
    | '/admin/accounting/expenses'
    | '/admin/accounting/journal'
    | '/admin/accounting/reports'
    | '/admin/cms/about'
    | '/admin/cms/fleet'
    | '/admin/cms/home'
    | '/admin/crm/campaigns'
    | '/admin/crm/leads'
    | '/admin/customers/$customerId'
    | '/admin/dashboard/commercial'
    | '/admin/dashboard/operations'
    | '/admin/fleet/categories'
    | '/admin/fleet/maintenance'
    | '/admin/hr/advances'
    | '/admin/hr/departments'
    | '/admin/hr/employees'
    | '/admin/hr/leaves'
    | '/admin/hr/loans'
    | '/admin/hr/payroll'
    | '/admin/orders/invoices'
    | '/admin/orders/manual'
    | '/admin/orders/online'
    | '/admin/orders/rentals'
    | '/admin/fleet/'
    | '/admin/fleet/vehicles/$unitId'
    | '/admin/fleet/vehicles/'
    | '/api/public/campaign/$slug/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/health'
    | '/admin/news'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/book/$vehicleId'
    | '/c/$slug'
    | '/fleet/$vehicleId'
    | '/news/$slug'
    | '/admin'
    | '/fleet'
    | '/news'
    | '/admin/accounting/coa'
    | '/admin/accounting/expenses'
    | '/admin/accounting/journal'
    | '/admin/accounting/reports'
    | '/admin/cms/about'
    | '/admin/cms/fleet'
    | '/admin/cms/home'
    | '/admin/crm/campaigns'
    | '/admin/crm/leads'
    | '/admin/customers/$customerId'
    | '/admin/dashboard/commercial'
    | '/admin/dashboard/operations'
    | '/admin/fleet/categories'
    | '/admin/fleet/maintenance'
    | '/admin/hr/advances'
    | '/admin/hr/departments'
    | '/admin/hr/employees'
    | '/admin/hr/leaves'
    | '/admin/hr/loans'
    | '/admin/hr/payroll'
    | '/admin/orders/invoices'
    | '/admin/orders/manual'
    | '/admin/orders/online'
    | '/admin/orders/rentals'
    | '/admin/fleet'
    | '/admin/fleet/vehicles/$unitId'
    | '/admin/fleet/vehicles'
    | '/api/public/campaign/$slug/view'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/health'
    | '/admin/news'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/book/$vehicleId'
    | '/c/$slug'
    | '/fleet/$vehicleId'
    | '/news/$slug'
    | '/admin/'
    | '/fleet/'
    | '/news/'
    | '/admin/accounting/coa'
    | '/admin/accounting/expenses'
    | '/admin/accounting/journal'
    | '/admin/accounting/reports'
    | '/admin/cms/about'
    | '/admin/cms/fleet'
    | '/admin/cms/home'
    | '/admin/crm/campaigns'
    | '/admin/crm/leads'
    | '/admin/customers/$customerId'
    | '/admin/dashboard/commercial'
    | '/admin/dashboard/operations'
    | '/admin/fleet/categories'
    | '/admin/fleet/maintenance'
    | '/admin/hr/advances'
    | '/admin/hr/departments'
    | '/admin/hr/employees'
    | '/admin/hr/leaves'
    | '/admin/hr/loans'
    | '/admin/hr/payroll'
    | '/admin/orders/invoices'
    | '/admin/orders/manual'
    | '/admin/orders/online'
    | '/admin/orders/rentals'
    | '/admin/fleet/'
    | '/admin/fleet/vehicles/$unitId'
    | '/admin/fleet/vehicles/'
    | '/api/public/campaign/$slug/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BookVehicleIdRoute: typeof BookVehicleIdRoute
  CSlugRoute: typeof CSlugRoute
  FleetVehicleIdRoute: typeof FleetVehicleIdRoute
  NewsSlugRoute: typeof NewsSlugRoute
  FleetIndexRoute: typeof FleetIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiPublicCampaignSlugViewRoute: typeof ApiPublicCampaignSlugViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$vehicleId': {
      id: '/fleet/$vehicleId'
      path: '/fleet/$vehicleId'
      fullPath: '/fleet/$vehicleId'
      preLoaderRoute: typeof FleetVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$vehicleId': {
      id: '/book/$vehicleId'
      path: '/book/$vehicleId'
      fullPath: '/book/$vehicleId'
      preLoaderRoute: typeof BookVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet/': {
      id: '/admin/fleet/'
      path: '/fleet'
      fullPath: '/admin/fleet/'
      preLoaderRoute: typeof AdminFleetIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/rentals': {
      id: '/admin/orders/rentals'
      path: '/orders/rentals'
      fullPath: '/admin/orders/rentals'
      preLoaderRoute: typeof AdminOrdersRentalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/online': {
      id: '/admin/orders/online'
      path: '/orders/online'
      fullPath: '/admin/orders/online'
      preLoaderRoute: typeof AdminOrdersOnlineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/manual': {
      id: '/admin/orders/manual'
      path: '/orders/manual'
      fullPath: '/admin/orders/manual'
      preLoaderRoute: typeof AdminOrdersManualRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/invoices': {
      id: '/admin/orders/invoices'
      path: '/orders/invoices'
      fullPath: '/admin/orders/invoices'
      preLoaderRoute: typeof AdminOrdersInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr/payroll': {
      id: '/admin/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/admin/hr/payroll'
      preLoaderRoute: typeof AdminHrPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr/loans': {
      id: '/admin/hr/loans'
      path: '/hr/loans'
      fullPath: '/admin/hr/loans'
      preLoaderRoute: typeof AdminHrLoansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr/leaves': {
      id: '/admin/hr/leaves'
      path: '/hr/leaves'
      fullPath: '/admin/hr/leaves'
      preLoaderRoute: typeof AdminHrLeavesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr/employees': {
      id: '/admin/hr/employees'
      path: '/hr/employees'
      fullPath: '/admin/hr/employees'
      preLoaderRoute: typeof AdminHrEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr/departments': {
      id: '/admin/hr/departments'
      path: '/hr/departments'
      fullPath: '/admin/hr/departments'
      preLoaderRoute: typeof AdminHrDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr/advances': {
      id: '/admin/hr/advances'
      path: '/hr/advances'
      fullPath: '/admin/hr/advances'
      preLoaderRoute: typeof AdminHrAdvancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet/maintenance': {
      id: '/admin/fleet/maintenance'
      path: '/fleet/maintenance'
      fullPath: '/admin/fleet/maintenance'
      preLoaderRoute: typeof AdminFleetMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet/categories': {
      id: '/admin/fleet/categories'
      path: '/fleet/categories'
      fullPath: '/admin/fleet/categories'
      preLoaderRoute: typeof AdminFleetCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/operations': {
      id: '/admin/dashboard/operations'
      path: '/dashboard/operations'
      fullPath: '/admin/dashboard/operations'
      preLoaderRoute: typeof AdminDashboardOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/commercial': {
      id: '/admin/dashboard/commercial'
      path: '/dashboard/commercial'
      fullPath: '/admin/dashboard/commercial'
      preLoaderRoute: typeof AdminDashboardCommercialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/crm/leads': {
      id: '/admin/crm/leads'
      path: '/crm/leads'
      fullPath: '/admin/crm/leads'
      preLoaderRoute: typeof AdminCrmLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/campaigns': {
      id: '/admin/crm/campaigns'
      path: '/crm/campaigns'
      fullPath: '/admin/crm/campaigns'
      preLoaderRoute: typeof AdminCrmCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/home': {
      id: '/admin/cms/home'
      path: '/cms/home'
      fullPath: '/admin/cms/home'
      preLoaderRoute: typeof AdminCmsHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/fleet': {
      id: '/admin/cms/fleet'
      path: '/cms/fleet'
      fullPath: '/admin/cms/fleet'
      preLoaderRoute: typeof AdminCmsFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/about': {
      id: '/admin/cms/about'
      path: '/cms/about'
      fullPath: '/admin/cms/about'
      preLoaderRoute: typeof AdminCmsAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounting/reports': {
      id: '/admin/accounting/reports'
      path: '/accounting/reports'
      fullPath: '/admin/accounting/reports'
      preLoaderRoute: typeof AdminAccountingReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounting/journal': {
      id: '/admin/accounting/journal'
      path: '/accounting/journal'
      fullPath: '/admin/accounting/journal'
      preLoaderRoute: typeof AdminAccountingJournalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounting/expenses': {
      id: '/admin/accounting/expenses'
      path: '/accounting/expenses'
      fullPath: '/admin/accounting/expenses'
      preLoaderRoute: typeof AdminAccountingExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounting/coa': {
      id: '/admin/accounting/coa'
      path: '/accounting/coa'
      fullPath: '/admin/accounting/coa'
      preLoaderRoute: typeof AdminAccountingCoaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet/vehicles/': {
      id: '/admin/fleet/vehicles/'
      path: '/fleet/vehicles'
      fullPath: '/admin/fleet/vehicles/'
      preLoaderRoute: typeof AdminFleetVehiclesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet/vehicles/$unitId': {
      id: '/admin/fleet/vehicles/$unitId'
      path: '/fleet/vehicles/$unitId'
      fullPath: '/admin/fleet/vehicles/$unitId'
      preLoaderRoute: typeof AdminFleetVehiclesUnitIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/campaign/$slug/view': {
      id: '/api/public/campaign/$slug/view'
      path: '/api/public/campaign/$slug/view'
      fullPath: '/api/public/campaign/$slug/view'
      preLoaderRoute: typeof ApiPublicCampaignSlugViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminHealthRoute: typeof AdminHealthRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountingCoaRoute: typeof AdminAccountingCoaRoute
  AdminAccountingExpensesRoute: typeof AdminAccountingExpensesRoute
  AdminAccountingJournalRoute: typeof AdminAccountingJournalRoute
  AdminAccountingReportsRoute: typeof AdminAccountingReportsRoute
  AdminCmsAboutRoute: typeof AdminCmsAboutRoute
  AdminCmsFleetRoute: typeof AdminCmsFleetRoute
  AdminCmsHomeRoute: typeof AdminCmsHomeRoute
  AdminCrmCampaignsRoute: typeof AdminCrmCampaignsRoute
  AdminCrmLeadsRoute: typeof AdminCrmLeadsRoute
  AdminDashboardCommercialRoute: typeof AdminDashboardCommercialRoute
  AdminDashboardOperationsRoute: typeof AdminDashboardOperationsRoute
  AdminFleetCategoriesRoute: typeof AdminFleetCategoriesRoute
  AdminFleetMaintenanceRoute: typeof AdminFleetMaintenanceRoute
  AdminHrAdvancesRoute: typeof AdminHrAdvancesRoute
  AdminHrDepartmentsRoute: typeof AdminHrDepartmentsRoute
  AdminHrEmployeesRoute: typeof AdminHrEmployeesRoute
  AdminHrLeavesRoute: typeof AdminHrLeavesRoute
  AdminHrLoansRoute: typeof AdminHrLoansRoute
  AdminHrPayrollRoute: typeof AdminHrPayrollRoute
  AdminOrdersInvoicesRoute: typeof AdminOrdersInvoicesRoute
  AdminOrdersManualRoute: typeof AdminOrdersManualRoute
  AdminOrdersOnlineRoute: typeof AdminOrdersOnlineRoute
  AdminOrdersRentalsRoute: typeof AdminOrdersRentalsRoute
  AdminFleetIndexRoute: typeof AdminFleetIndexRoute
  AdminFleetVehiclesUnitIdRoute: typeof AdminFleetVehiclesUnitIdRoute
  AdminFleetVehiclesIndexRoute: typeof AdminFleetVehiclesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminHealthRoute: AdminHealthRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountingCoaRoute: AdminAccountingCoaRoute,
  AdminAccountingExpensesRoute: AdminAccountingExpensesRoute,
  AdminAccountingJournalRoute: AdminAccountingJournalRoute,
  AdminAccountingReportsRoute: AdminAccountingReportsRoute,
  AdminCmsAboutRoute: AdminCmsAboutRoute,
  AdminCmsFleetRoute: AdminCmsFleetRoute,
  AdminCmsHomeRoute: AdminCmsHomeRoute,
  AdminCrmCampaignsRoute: AdminCrmCampaignsRoute,
  AdminCrmLeadsRoute: AdminCrmLeadsRoute,
  AdminDashboardCommercialRoute: AdminDashboardCommercialRoute,
  AdminDashboardOperationsRoute: AdminDashboardOperationsRoute,
  AdminFleetCategoriesRoute: AdminFleetCategoriesRoute,
  AdminFleetMaintenanceRoute: AdminFleetMaintenanceRoute,
  AdminHrAdvancesRoute: AdminHrAdvancesRoute,
  AdminHrDepartmentsRoute: AdminHrDepartmentsRoute,
  AdminHrEmployeesRoute: AdminHrEmployeesRoute,
  AdminHrLeavesRoute: AdminHrLeavesRoute,
  AdminHrLoansRoute: AdminHrLoansRoute,
  AdminHrPayrollRoute: AdminHrPayrollRoute,
  AdminOrdersInvoicesRoute: AdminOrdersInvoicesRoute,
  AdminOrdersManualRoute: AdminOrdersManualRoute,
  AdminOrdersOnlineRoute: AdminOrdersOnlineRoute,
  AdminOrdersRentalsRoute: AdminOrdersRentalsRoute,
  AdminFleetIndexRoute: AdminFleetIndexRoute,
  AdminFleetVehiclesUnitIdRoute: AdminFleetVehiclesUnitIdRoute,
  AdminFleetVehiclesIndexRoute: AdminFleetVehiclesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BookVehicleIdRoute: BookVehicleIdRoute,
  CSlugRoute: CSlugRoute,
  FleetVehicleIdRoute: FleetVehicleIdRoute,
  NewsSlugRoute: NewsSlugRoute,
  FleetIndexRoute: FleetIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiPublicCampaignSlugViewRoute: ApiPublicCampaignSlugViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
